"""
Tests for the Audit Reporter module.

**Feature: documentation-validation, Property 21: Finding Completeness**
**Feature: documentation-validation, Property 22: Fix Suggestion Generation**
**Validates: Requirements 10.1, 10.2, 10.3, 10.4**
"""

from hypothesis import given, strategies as st, settings

from udl_rating_framework.validation.audit_reporter import (
    AuditReporter,
    AuditReport,
    Finding,
    FindingCategory,
    Severity,
    ResolutionStatus,
    SourceLocation,
    FixSuggestionGenerator,
)


class TestFindingCompleteness:
    """
    Tests for Property 21: Finding Completeness.
    
    **Feature: documentation-validation, Property 21: Finding Completeness**
    **Validates: Requirements 10.2, 10.3**
    
    For any validation finding generated by the audit system, it must include
    severity category, file location, and line number.
    """
    
    @given(
        category=st.sampled_from(list(FindingCategory)),
        severity=st.sampled_from(list(Severity)),
        file_path=st.text(min_size=1, max_size=100).filter(lambda x: x.strip()),
        line_number=st.one_of(st.none(), st.integers(min_value=1, max_value=10000)),
        description=st.text(min_size=1, max_size=500).filter(lambda x: x.strip()),
    )
    @settings(max_examples=100)
    def test_finding_has_required_fields(
        self, category, severity, file_path, line_number, description
    ):
        """
        **Feature: documentation-validation, Property 21: Finding Completeness**
        **Validates: Requirements 10.2, 10.3**
        
        For any finding, it must have severity, file location, and description.
        """
        reporter = AuditReporter()
        
        finding = reporter.add_finding(
            category=category,
            severity=severity,
            file_path=file_path,
            line_number=line_number,
            description=description,
        )
        
        # Property 21: Finding must have required fields
        assert finding.id is not None and len(finding.id) > 0
        assert finding.category is not None
        assert finding.severity is not None
        assert finding.source_location is not None
        assert finding.source_location.file_path is not None
        assert finding.description is not None and len(finding.description) > 0
    
    @given(
        category=st.sampled_from(list(FindingCategory)),
        severity=st.sampled_from(list(Severity)),
    )
    @settings(max_examples=50)
    def test_finding_id_is_unique(self, category, severity):
        """
        **Feature: documentation-validation, Property 21: Finding Completeness**
        **Validates: Requirements 10.2**
        
        Each finding must have a unique ID.
        """
        reporter = AuditReporter()
        
        # Add multiple findings
        findings = []
        for i in range(5):
            finding = reporter.add_finding(
                category=category,
                severity=severity,
                file_path=f"test_file_{i}.py",
                description=f"Test finding {i}",
            )
            findings.append(finding)
        
        # All IDs should be unique
        ids = [f.id for f in findings]
        assert len(ids) == len(set(ids)), "Finding IDs must be unique"
    
    def test_finding_to_dict_completeness(self):
        """
        **Feature: documentation-validation, Property 21: Finding Completeness**
        **Validates: Requirements 10.2, 10.3**
        
        Finding serialization must include all required fields.
        """
        finding = Finding(
            id="TEST-0001",
            category=FindingCategory.LINK,
            severity=Severity.MAJOR,
            source_location=SourceLocation(file_path="test.md", line_number=42),
            description="Test finding",
            expected="expected_value",
            actual="actual_value",
            suggestion="Fix suggestion",
            requirement_ref="1.2",
        )
        
        data = finding.to_dict()
        
        # Required fields
        assert "id" in data
        assert "category" in data
        assert "severity" in data
        assert "source_file" in data
        assert "source_line" in data
        assert "description" in data
        
        # Optional fields
        assert "expected" in data
        assert "actual" in data
        assert "suggestion" in data
        assert "requirement_ref" in data
        assert "status" in data


class TestFixSuggestionGeneration:
    """
    Tests for Property 22: Fix Suggestion Generation.
    
    **Feature: documentation-validation, Property 22: Fix Suggestion Generation**
    **Validates: Requirements 10.4**
    
    For any common issue type, the system should generate a fix suggestion.
    """
    
    @given(category=st.sampled_from(list(FindingCategory)))
    @settings(max_examples=100)
    def test_all_categories_have_suggestions(self, category):
        """
        **Feature: documentation-validation, Property 22: Fix Suggestion Generation**
        **Validates: Requirements 10.4**
        
        For any finding category, a suggestion should be generated.
        """
        generator = FixSuggestionGenerator()
        
        finding = Finding(
            id="TEST-0001",
            category=category,
            severity=Severity.MAJOR,
            source_location=SourceLocation(file_path="test.py"),
            description="Test finding for category",
        )
        
        suggestion = generator.generate_suggestion(finding)
        
        # Property 22: Every category should have a suggestion
        assert suggestion is not None
        assert len(suggestion) > 0
    
    def test_broken_link_suggestion(self):
        """
        **Feature: documentation-validation, Property 22: Fix Suggestion Generation**
        **Validates: Requirements 10.4**
        
        Broken link findings should get appropriate suggestions.
        """
        generator = FixSuggestionGenerator()
        
        finding = Finding(
            id="LINK-0001",
            category=FindingCategory.LINK,
            severity=Severity.MAJOR,
            source_location=SourceLocation(file_path="README.md", line_number=10),
            description="Broken file link to docs/missing.md",
            expected="docs/missing.md",
        )
        
        suggestion = generator.generate_suggestion(finding)
        
        assert suggestion is not None
        assert len(suggestion) > 0
    
    def test_missing_docstring_suggestion(self):
        """
        **Feature: documentation-validation, Property 22: Fix Suggestion Generation**
        **Validates: Requirements 10.4**
        
        Missing docstring findings should get appropriate suggestions.
        """
        generator = FixSuggestionGenerator()
        
        finding = Finding(
            id="API-0001",
            category=FindingCategory.API,
            severity=Severity.MINOR,
            source_location=SourceLocation(file_path="module.py", line_number=50),
            description="Missing docstring for function calculate",
        )
        
        suggestion = generator.generate_suggestion(finding)
        
        assert suggestion is not None
        assert "docstring" in suggestion.lower() or "documentation" in suggestion.lower()
    
    def test_signature_mismatch_suggestion(self):
        """
        **Feature: documentation-validation, Property 22: Fix Suggestion Generation**
        **Validates: Requirements 10.4**
        
        Signature mismatch findings should get appropriate suggestions.
        """
        generator = FixSuggestionGenerator()
        
        finding = Finding(
            id="API-0002",
            category=FindingCategory.API,
            severity=Severity.MAJOR,
            source_location=SourceLocation(file_path="module.py", line_number=100),
            description="Signature mismatch for function process",
            expected="process(data: str) -> int",
            actual="process(data: str, flag: bool) -> int",
        )
        
        suggestion = generator.generate_suggestion(finding)
        
        assert suggestion is not None
        assert len(suggestion) > 0
    
    @given(
        category=st.sampled_from(list(FindingCategory)),
        severity=st.sampled_from(list(Severity)),
        description=st.text(min_size=10, max_size=200).filter(lambda x: x.strip()),
    )
    @settings(max_examples=100)
    def test_suggestion_is_non_empty_string(self, category, severity, description):
        """
        **Feature: documentation-validation, Property 22: Fix Suggestion Generation**
        **Validates: Requirements 10.4**
        
        For any finding, the generated suggestion must be a non-empty string.
        """
        generator = FixSuggestionGenerator()
        
        finding = Finding(
            id="TEST-0001",
            category=category,
            severity=severity,
            source_location=SourceLocation(file_path="test.py"),
            description=description,
        )
        
        suggestion = generator.generate_suggestion(finding)
        
        assert isinstance(suggestion, str)
        assert len(suggestion.strip()) > 0


class TestAuditReporter:
    """Tests for the AuditReporter class."""
    
    def test_report_generation(self):
        """Test that reports are generated correctly."""
        reporter = AuditReporter()
        
        reporter.add_finding(
            category=FindingCategory.LINK,
            severity=Severity.MAJOR,
            file_path="README.md",
            line_number=10,
            description="Broken link",
        )
        
        reporter.add_finding(
            category=FindingCategory.API,
            severity=Severity.MINOR,
            file_path="module.py",
            description="Missing docstring",
        )
        
        # Generate markdown report
        md_report = reporter.generate_markdown_report()
        
        assert "# Documentation Audit Report" in md_report
        assert "Total findings: **2**" in md_report
        assert "LINK-0001" in md_report
        assert "API-0002" in md_report
    
    def test_categorize_findings(self):
        """Test finding categorization by severity."""
        reporter = AuditReporter()
        
        reporter.add_finding(
            category=FindingCategory.LINK,
            severity=Severity.CRITICAL,
            file_path="test.md",
            description="Critical issue",
        )
        
        reporter.add_finding(
            category=FindingCategory.API,
            severity=Severity.MAJOR,
            file_path="test.py",
            description="Major issue",
        )
        
        reporter.add_finding(
            category=FindingCategory.DOCSTRING,
            severity=Severity.MINOR,
            file_path="test.py",
            description="Minor issue",
        )
        
        categorized = reporter.categorize_findings()
        
        assert len(categorized[Severity.CRITICAL]) == 1
        assert len(categorized[Severity.MAJOR]) == 1
        assert len(categorized[Severity.MINOR]) == 1
        assert len(categorized[Severity.INFO]) == 0
    
    def test_recommendations_generation(self):
        """Test that recommendations are generated based on findings."""
        reporter = AuditReporter()
        
        # Add critical finding
        reporter.add_finding(
            category=FindingCategory.LINK,
            severity=Severity.CRITICAL,
            file_path="test.md",
            description="Critical broken link",
        )
        
        recommendations = reporter.generate_recommendations()
        
        assert len(recommendations) > 0
        assert any("critical" in r.lower() for r in recommendations)
    
    def test_json_report_generation(self):
        """Test JSON report generation."""
        reporter = AuditReporter()
        
        reporter.add_finding(
            category=FindingCategory.LINK,
            severity=Severity.MAJOR,
            file_path="README.md",
            description="Broken link",
        )
        
        json_report = reporter.generate_json_report()
        
        import json
        data = json.loads(json_report)
        
        assert "timestamp" in data
        assert "findings" in data
        assert len(data["findings"]) == 1
        assert data["findings"][0]["category"] == "link"


class TestAuditReport:
    """Tests for the AuditReport dataclass."""
    
    def test_summary_updates(self):
        """Test that summary is updated when findings are added."""
        report = AuditReport()
        
        finding = Finding(
            id="TEST-0001",
            category=FindingCategory.LINK,
            severity=Severity.MAJOR,
            source_location=SourceLocation(file_path="test.md"),
            description="Test finding",
        )
        
        report.add_finding(finding)
        
        assert report.summary["total"] == 1
        assert report.summary["major"] == 1
        assert report.summary["category_link"] == 1
    
    def test_get_findings_by_severity(self):
        """Test filtering findings by severity."""
        report = AuditReport()
        
        report.add_finding(Finding(
            id="TEST-0001",
            category=FindingCategory.LINK,
            severity=Severity.MAJOR,
            source_location=SourceLocation(file_path="test.md"),
            description="Major finding",
        ))
        
        report.add_finding(Finding(
            id="TEST-0002",
            category=FindingCategory.API,
            severity=Severity.MINOR,
            source_location=SourceLocation(file_path="test.py"),
            description="Minor finding",
        ))
        
        major_findings = report.get_findings_by_severity(Severity.MAJOR)
        minor_findings = report.get_findings_by_severity(Severity.MINOR)
        
        assert len(major_findings) == 1
        assert len(minor_findings) == 1
        assert major_findings[0].id == "TEST-0001"
    
    def test_get_open_findings(self):
        """Test filtering open findings."""
        report = AuditReport()
        
        report.add_finding(Finding(
            id="TEST-0001",
            category=FindingCategory.LINK,
            severity=Severity.MAJOR,
            source_location=SourceLocation(file_path="test.md"),
            description="Open finding",
            status=ResolutionStatus.OPEN,
        ))
        
        report.add_finding(Finding(
            id="TEST-0002",
            category=FindingCategory.API,
            severity=Severity.MINOR,
            source_location=SourceLocation(file_path="test.py"),
            description="Resolved finding",
            status=ResolutionStatus.RESOLVED,
        ))
        
        open_findings = report.get_open_findings()
        
        assert len(open_findings) == 1
        assert open_findings[0].id == "TEST-0001"
